.github/workflows/ci-docker.yml, .github/workflows/publish.yml
=> GH-3 CI/CD for Docker images

Makefile, go.mod, go.sum, internal/api/api.go
=> feat: close Ouroboros connection after submitting transaction

internal/api/api.go
=> feat: tx_failure_count metric for failed transactions

go.mod, go.sum, internal/config/config.go
Use libada's ProtocolMagic function rather than our constants.
=> feat: use libada-go for protocol magic

internal/api/api.go
=> fix: expose metrics on :8081/

internal/config/config.go
=> fix: use CARDANO_NETWORK envvar

internal/api/api.go
=> chore: refactor/rename variables for clarity

.github/workflows/golangci-lint.yml, Dockerfile
=> chore: upgrade golang to 1.18

go.mod, go.sum, internal/api/api.go
=> chore: update go-ouroboros-network to 0.14.0

go.mod, go.sum, internal/config/config.go
=> feat: support preprod and preview

README.md
=> feat: initial README, fixes #5

README.md
=> fix: readme formatting

config.yaml.example
=> fix: update config.yaml.example TCP vars

config.yaml.example, internal/api/api.go, internal/config/config.go
=> feat: optionally log /healthcheck, fixes #55

go.mod, go.sum, internal/api/api.go
=> Parse transaction to determine type/era

go.mod, go.sum, internal/api/api.go
=> feat: better handling of reject reason parse failure

.github/workflows/publish.yml
=> ci: update publishing for docker images and releases

go.mod, go.sum, internal/api/api.go
=> fix: set response content-type to application/json, fixes #59

go.mod, go.sum
=> chore: downgrade ouroboros-network to 0.16.1

internal/config/config.go
=> feat: check node at start

internal/api/api.go
=> fix: valid JSON requires the strings be quoted

.github/workflows/golangci-lint.yml
=> ci: golang matrix for testing

internal/api/api.go
=> feat: return error cbor on request using accept header

go.mod, go.sum, internal/api/api.go
=> feat: support for parsing TX reject reason CBOR

config.yaml.example
=> chore: document node network settings in example

README.md
=> chore: document end-to-end use with cardano-node

.github/workflows/ci-docker.yml, .github/workflows/publish-docker-images.yml
=> ci: upgrade docker actions

README.md
=> docs: usage with local cardano-node

go.mod, go.sum, internal/config/config.go
Removes the prerelease dependency on libada-go
=> feat: use gouroboros for network magic

internal/api/api.go
This allows the metrics in #251 to be displayed.
=> fix: cors for htmx

internal/api/static/index.html
- cpu calculation for percentage conversion
- fixes #263
=> fix: cpu value is now a percentage

internal/api/static/index.html
=> fix: scaling for transaction metrics
